#!/usr/bin/env node
// Single source of truth for the project version string: 0.<config-schema>.<build>.
//
//  - config-schema is the firmware's CFG_VERSION (main/app_config.c) — the same
//    number bumped on every config change, so the version can never drift from
//    the on-device schema.
//  - build is a monotonic counter (web/.build_version), incremented ONCE per
//    production build. The counter records the config version it was counting
//    under ("<cfg> <build>") so build numbering restarts at 0 whenever
//    CFG_VERSION bumps — a schema change starts a new minor line (0.13.42 →
//    0.14.1, not 0.14.43). An old single-number file resets.
//
// Invoked at build time by CMake (see main/CMakeLists.txt). Writes a C header
// the firmware compiles in AND a plain-text file the Vite build reads, so the
// footer and the firmware always report the identical string. Run once per
// build, so calling it is what advances the build number.
//
// Usage: node gen-version.mjs <app_config.c> <counterFile> <out.h> <out.txt>

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const [, , cfgPath, counterPath, headerOut, txtOut] = process.argv;
if (!cfgPath || !counterPath) {
  console.error('usage: gen-version.mjs <app_config.c> <counterFile> [out.h] [out.txt]');
  process.exit(2);
}

let cfg = '?';
try {
  const m = readFileSync(cfgPath, 'utf8').match(/#define\s+CFG_VERSION\s+(\d+)/);
  if (m) cfg = m[1];
} catch { /* leave '?' if the file moved — visible, not fatal */ }

let savedCfg = null, build = 0;
try {
  const parts = readFileSync(counterPath, 'utf8').trim().split(/\s+/);
  if (parts.length >= 2) { savedCfg = parts[0]; build = parseInt(parts[1], 10) || 0; }
} catch { /* first build */ }
if (savedCfg !== cfg) build = 0;   // config schema changed → restart build numbering
build += 1;
try { writeFileSync(counterPath, `${cfg} ${build}\n`); } catch { /* read-only FS: still emit prior */ }

const version = `0.${cfg}.${build}`;

function emit(path, contents) {
  if (!path) return;
  try { mkdirSync(dirname(path), { recursive: true }); } catch { /* exists */ }
  writeFileSync(path, contents);
}

emit(headerOut,
  `/* Generated by tools/gen-version.mjs — do not edit. */\n` +
  `#pragma once\n` +
  `#define CARVISTON_VERSION "${version}"\n`);
emit(txtOut, version);

process.stdout.write(version + '\n');
